// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProiectDAW.Entities;

namespace ProiectDAW.Migrations
{
    [DbContext(typeof(ProiectDAWContext))]
    [Migration("20220116103523_Added_Adress")]
    partial class Added_Adress
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProiectDAW.Entities.ServiceAutoAdress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service_AutoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Street_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Service_AutoId")
                        .IsUnique()
                        .HasFilter("[Service_AutoId] IS NOT NULL");

                    b.ToTable("ServiceAutoAdresses");
                });

            modelBuilder.Entity("ProiectDAW.Entities.Service_Auto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Service_Autos");
                });

            modelBuilder.Entity("ProiectDAW.Entities.ServiceAutoAdress", b =>
                {
                    b.HasOne("ProiectDAW.Entities.Service_Auto", "Service_Auto")
                        .WithOne("ServiceAutoAdress")
                        .HasForeignKey("ProiectDAW.Entities.ServiceAutoAdress", "Service_AutoId");

                    b.Navigation("Service_Auto");
                });

            modelBuilder.Entity("ProiectDAW.Entities.Service_Auto", b =>
                {
                    b.Navigation("ServiceAutoAdress");
                });
#pragma warning restore 612, 618
        }
    }
}
