// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProiectDAW.Entities;

namespace ProiectDAW.Migrations
{
    [DbContext(typeof(ProiectDAWContext))]
    [Migration("20220117120544_testtest")]
    partial class testtest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProiectDAW.Entities.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDay")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ProiectDAW.Entities.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service_AutoId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Service_AutoId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ProiectDAW.Entities.ServiceAutoAdress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service_AutoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Street_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Service_AutoId")
                        .IsUnique()
                        .HasFilter("[Service_AutoId] IS NOT NULL");

                    b.ToTable("ServiceAutoAdresses");
                });

            modelBuilder.Entity("ProiectDAW.Entities.Service_Auto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Service_Autos");
                });

            modelBuilder.Entity("ProiectDAW.Entities.Service_AutoClient", b =>
                {
                    b.Property<string>("Service_AutoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Service_AutoId", "ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("Service_AutoClients");
                });

            modelBuilder.Entity("ProiectDAW.Entities.Employee", b =>
                {
                    b.HasOne("ProiectDAW.Entities.Service_Auto", "Service_Auto")
                        .WithMany("Employees")
                        .HasForeignKey("Service_AutoId");

                    b.Navigation("Service_Auto");
                });

            modelBuilder.Entity("ProiectDAW.Entities.ServiceAutoAdress", b =>
                {
                    b.HasOne("ProiectDAW.Entities.Service_Auto", "Service_Auto")
                        .WithOne("ServiceAutoAdress")
                        .HasForeignKey("ProiectDAW.Entities.ServiceAutoAdress", "Service_AutoId");

                    b.Navigation("Service_Auto");
                });

            modelBuilder.Entity("ProiectDAW.Entities.Service_AutoClient", b =>
                {
                    b.HasOne("ProiectDAW.Entities.Client", "Client")
                        .WithMany("Service_AutoClients")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProiectDAW.Entities.Service_Auto", "Service_Auto")
                        .WithMany("Service_AutoClients")
                        .HasForeignKey("Service_AutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Service_Auto");
                });

            modelBuilder.Entity("ProiectDAW.Entities.Client", b =>
                {
                    b.Navigation("Service_AutoClients");
                });

            modelBuilder.Entity("ProiectDAW.Entities.Service_Auto", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Service_AutoClients");

                    b.Navigation("ServiceAutoAdress");
                });
#pragma warning restore 612, 618
        }
    }
}
